[package]
name = "matrix-visualisations-backend"
version = "0.1.0"
authors = ["Eisha Chen-yen-su <chenyensu0@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "1.0"
postgres = "0.15"
serde = "1"
serde_derive = "1"
serde_json = "1"
