[package]
name = "matrix-visualisations-backend"
version = "0.1.0"
authors = ["Eisha Chen-yen-su <chenyensu0@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "1.0"
futures = "0.1"
futures-cpupool = "0.1"
r2d2 = "0.8"
r2d2_postgres = "0.14"
serde = "1"
serde_derive = "1"
serde_json = "1"
